### ISSUE TITLE
How to Run the Example Project

### ISSUE THREAD

**Issue by vc7** [soffes/SAMCoreImageView#2]
I have cloned this repo and went into the example folder, and trying `pod install` to run the pod, but it prump not found for me, 

``` sh
Fetching podspec for `SAMCoreImageView` from `../`
[!] Unable to satisfy the following requirements:
- `SAMCoreImageView (from `../`)` required by `Podfile`
```

but the required folder is there, help me please :smile:

**Comment by cameronehrlich** [comment]
Yeah, the example project aint all there.
